---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 84.201.135.38
      ansible_connection: ssh
      ansible_user: serg
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub
vector:
  hosts:
    clickhouse-02:
      ansible_host: 89.169.128.201
      ansible_connection: ssh
      ansible_user: serg
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub
lighthouse:
  hosts:
    clickhouse-03:
      ansible_host: 89.169.148.167
      ansible_connection: ssh
      ansible_user: serg
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub192.168.0.220